services:
  - type: web
    name: travelgpt
    runtime: python
    region: singapore           # change to: oregon, frankfurt, ohio, virginia
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER
        value: "true"
      - key: IBM_API_KEY
        sync: false
      - key: IBM_PROJECT_ID
        sync: false
      - key: IBM_REGION
        value: "us-south"
      - key: SECRET_KEY
        generateValue: true
